In [1]:
import pandas as pd
import requests

def get_precipitation(start_dt , end_dt , lon , lat):

    url = (f"https://power.larc.nasa.gov/api/temporal/daily/point?start={start_dt}&end={end_dt}&latitude={lat}&longitude={lon}&community=ag&parameters=PRECTOTCORR&format=json&header=true")


    response = requests.get(url , timeout = 20)

    response.raise_for_status()

    data = response.json()
    print(data)
    
    coordinates = data['geometry']['coordinates']    

    coordinate_df = pd.DataFrame([coordinates ], columns = ['Latitude' , 'Longitude' , 'Elevation(in m)'])
    
    df = data['properties']['parameter']['PRECTOTCORR']
    precipation_df = pd.DataFrame( list(df.items()),
                                   columns = ["date", "precipitation"])

    return precipation_df , coordinate_df

get_precipitation( 19810101 , 20251230 ,20.593684 ,79 )

{'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [20.594, 79.0, 209.58]}, 'properties': {'parameter': {'PRECTOTCORR': {'19810101': 1.67, '19810102': 0.55, '19810103': 0.92, '19810104': 0.44, '19810105': 0.35, '19810106': 0.43, '19810107': 0.63, '19810108': 3.78, '19810109': 5.04, '19810110': 1.06, '19810111': 0.64, '19810112': 0.26, '19810113': 0.65, '19810114': 1.1, '19810115': 0.59, '19810116': 0.83, '19810117': 0.9, '19810118': 0.89, '19810119': 0.39, '19810120': 3.39, '19810121': 1.44, '19810122': 2.9, '19810123': 8.79, '19810124': 1.04, '19810125': 0.83, '19810126': 1.64, '19810127': 1.85, '19810128': 0.65, '19810129': 0.43, '19810130': 0.43, '19810131': 1.46, '19810201': 9.9, '19810202': 0.85, '19810203': 3.41, '19810204': 0.79, '19810205': 0.67, '19810206': 3.01, '19810207': 8.46, '19810208': 12.91, '19810209': 7.97, '19810210': 5.5, '19810211': 0.46, '19810212': 0.53, '19810213': 1.2, '19810214': 1.51, '19810215': 0.58, '19810216': 5.01, '19810217': 1.57, '19810218': 1.58, '19810219': 2.27, '19810220': 2.06, '19810221': 9.76, '19810222': 1.32, '19810223': 1.4, '19810224': 0.62, '19810225': 0.44, '19810226': 5.21, '19810227': 0.49, '19810228': 1.0, '19810301': 0.68, '19810302': 0.46, '19810303': 0.39, '19810304': 0.59, '19810305': 1.36, '19810306': 2.39, '19810307': 5.42, '19810308': 5.38, '19810309': 1.92, '19810310': 1.7, '19810311': 2.12, '19810312': 3.29, '19810313': 1.17, '19810314': 0.77, '19810315': 0.63, '19810316': 0.77, '19810317': 0.74, '19810318': 0.79, '19810319': 1.14, '19810320': 0.81, '19810321': 0.84, '19810322': 0.68, '19810323': 0.57, '19810324': 0.28, '19810325': 0.26, '19810326': 0.42, '19810327': 0.07, '19810328': 1.07, '19810329': 6.5, '19810330': 0.22, '19810331': 0.13, '19810401': 0.81, '19810402': 0.59, '19810403': 0.9, '19810404': 3.44, '19810405': 12.85, '19810406': 1.69, '19810407': 0.24, '19810408': 0.42, '19810409': 3.51, '19810410': 3.0, '19810411': 0.16, '19810412': 0.58, '19810413': 0.61, '19810414': 0.19, '19810415': 0.15, '19810416': 1.78, '19810417': 1.73, '19810418': 0.28, '19810419': 0.38, '19810420': 0.69, '19810421': 0.53, '19810422': 1.0, '19810423': 0.81, '19810424': 0.39, '19810425': 0.92, '19810426': 0.64, '19810427': 0.38, '19810428': 0.38, '19810429': 0.52, '19810430': 0.46, '19810501': 0.3, '19810502': 0.8, '19810503': 3.69, '19810504': 0.89, '19810505': 0.55, '19810506': 0.33, '19810507': 0.32, '19810508': 0.07, '19810509': 0.44, '19810510': 0.69, '19810511': 0.17, '19810512': 1.35, '19810513': 0.7, '19810514': 0.05, '19810515': 2.79, '19810516': 2.99, '19810517': 0.21, '19810518': 0.1, '19810519': 0.05, '19810520': 3.41, '19810521': 2.45, '19810522': 3.55, '19810523': 0.06, '19810524': 0.15, '19810525': 0.47, '19810526': 0.06, '19810527': 0.03, '19810528': 0.19, '19810529': 0.3, '19810530': 2.31, '19810531': 0.38, '19810601': 0.11, '19810602': 0.51, '19810603': 2.05, '19810604': 1.19, '19810605': 2.09, '19810606': 4.85, '19810607': 3.49, '19810608': 1.98, '19810609': 4.23, '19810610': 3.56, '19810611': 25.65, '19810612': 1.85, '19810613': 6.89, '19810614': 2.14, '19810615': 5.45, '19810616': 10.88, '19810617': 1.67, '19810618': 0.27, '19810619': 0.6, '19810620': 0.42, '19810621': 0.16, '19810622': 0.52, '19810623': 0.07, '19810624': 0.47, '19810625': 1.05, '19810626': 0.01, '19810627': 0.02, '19810628': 0.03, '19810629': 0.53, '19810630': 0.21, '19810701': 0.01, '19810702': 0.01, '19810703': 0.01, '19810704': 0.19, '19810705': 5.83, '19810706': 4.91, '19810707': 0.02, '19810708': 0.19, '19810709': 0.21, '19810710': 1.94, '19810711': 1.74, '19810712': 3.34, '19810713': 1.08, '19810714': 0.13, '19810715': 0.52, '19810716': 0.26, '19810717': 0.58, '19810718': 0.07, '19810719': 0.13, '19810720': 0.24, '19810721': 0.43, '19810722': 0.48, '19810723': 0.02, '19810724': 19.67, '19810725': 0.14, '19810726': 0.96, '19810727': 2.21, '19810728': 9.06, '19810729': 0.3, '19810730': 0.58, '19810731': 0.34, '19810801': 0.1, '19810802': 0.65, '19810803': 1.01, '19810804': 13.29, '19810805': 2.62, '19810806': 0.42, '19810807': 0.18, '19810808': 0.03, '19810809': 0.23, '19810810': 1.28, '19810811': 0.4, '19810812': 0.52, '19810813': 5.66, '19810814': 0.4, '19810815': 0.29, '19810816': 1.41, '19810817': 0.1, '19810818': 0.07, '19810819': 0.02, '19810820': 0.1, '19810821': 0.01, '19810822': 0.01, '19810823': 0.21, '19810824': 0.29, '19810825': 0.57, '19810826': 0.61, '19810827': 0.13, '19810828': 1.12, '19810829': 0.74, '19810830': 9.86, '19810831': 3.05, '19810901': 0.7, '19810902': 1.43, '19810903': 1.67, '19810904': 2.7, '19810905': 11.07, '19810906': 6.03, '19810907': 5.66, '19810908': 2.08, '19810909': 2.81, '19810910': 1.83, '19810911': 1.46, '19810912': 0.89, '19810913': 0.82, '19810914': 0.21, '19810915': 0.25, '19810916': 0.79, '19810917': 0.24, '19810918': 3.75, '19810919': 16.33, '19810920': 1.49, '19810921': 0.45, '19810922': 8.75, '19810923': 2.5, '19810924': 3.8, '19810925': 0.75, '19810926': 7.44, '19810927': 0.29, '19810928': 0.25, '19810929': 0.27, '19810930': 0.58, '19811001': 0.3, '19811002': 0.14, '19811003': 0.94, '19811004': 2.11, '19811005': 0.76, '19811006': 1.03, '19811007': 1.05, '19811008': 1.48, '19811009': 1.58, '19811010': 1.58, '19811011': 4.24, '19811012': 4.08, '19811013': 3.29, '19811014': 8.99, '19811015': 1.53, '19811016': 2.86, '19811017': 0.68, '19811018': 1.4, '19811019': 1.79, '19811020': 1.13, '19811021': 0.17, '19811022': 0.16, '19811023': 0.2, '19811024': 0.57, '19811025': 0.5, '19811026': 0.78, '19811027': 1.04, '19811028': 0.67, '19811029': 0.14, '19811030': 0.8, '19811031': 1.94, '19811101': 1.55, '19811102': 0.73, '19811103': 1.02, '19811104': 0.41, '19811105': 0.54, '19811106': 0.25, '19811107': 1.18, '19811108': 1.59, '19811109': 2.8, '19811110': 6.69, '19811111': 1.93, '19811112': 0.88, '19811113': 0.98, '19811114': 0.89, '19811115': 3.54, '19811116': 6.76, '19811117': 6.22, '19811118': 1.45, '19811119': 5.08, '19811120': 12.91, '19811121': 5.72, '19811122': 5.45, '19811123': 2.88, '19811124': 1.75, '19811125': 0.68, '19811126': 0.28, '19811127': 0.6, '19811128': 0.87, '19811129': 0.3, '19811130': 1.38, '19811201': 2.59, '19811202': 1.46, '19811203': 1.03, '19811204': 0.51, '19811205': 0.31, '19811206': 0.79, '19811207': 0.7, '19811208': 0.83, '19811209': 1.37, '19811210': 1.7, '19811211': 1.09, '19811212': 0.68, '19811213': 0.63, '19811214': 0.7, '19811215': 0.78, '19811216': 0.7, '19811217': 0.76, '19811218': 0.71, '19811219': 0.83, '19811220': 0.65, '19811221': 2.3, '19811222': 4.61, '19811223': 0.28, '19811224': 0.3, '19811225': 0.29, '19811226': 0.41, '19811227': 1.63, '19811228': 0.49, '19811229': 0.35, '19811230': 0.45, '19811231': 0.73, '19820101': 1.05, '19820102': 0.16, '19820103': 0.58, '19820104': 0.26, '19820105': 0.54, '19820106': 0.39, '19820107': 1.57, '19820108': 0.37, '19820109': 0.34, '19820110': 1.88, '19820111': 1.77, '19820112': 0.77, '19820113': 0.67, '19820114': 3.44, '19820115': 1.16, '19820116': 6.01, '19820117': 5.93, '19820118': 4.68, '19820119': 0.36, '19820120': 0.63, '19820121': 0.75, '19820122': 0.8, '19820123': 0.9, '19820124': 0.92, '19820125': 1.26, '19820126': 0.81, '19820127': 0.61, '19820128': 0.39, '19820129': 0.46, '19820130': 0.44, '19820131': 0.55, '19820201': 0.53, '19820202': 0.42, '19820203': 0.67, '19820204': 0.37, '19820205': 0.11, '19820206': 0.56, '19820207': 0.53, '19820208': 1.0, '19820209': 2.94, '19820210': 10.11, '19820211': 1.08, '19820212': 2.91, '19820213': 0.36, '19820214': 0.33, '19820215': 0.42, '19820216': 0.28, '19820217': 0.21, '19820218': 1.99, '19820219': 0.46, '19820220': 0.59, '19820221': 2.17, '19820222': 2.34, '19820223': 0.52, '19820224': 0.93, '19820225': 0.5, '19820226': 0.59, '19820227': 3.16, '19820228': 4.8, '19820301': 8.98, '19820302': 1.23, '19820303': 0.64, '19820304': 0.35, '19820305': 0.65, '19820306': 0.45, '19820307': 5.01, '19820308': 0.87, '19820309': 1.75, '19820310': 1.8, '19820311': 0.62, '19820312': 0.72, '19820313': 1.76, '19820314': 0.78, '19820315': 3.34, '19820316': 3.63, '19820317': 1.21, '19820318': 0.61, '19820319': 0.26, '19820320': 0.24, '19820321': 0.33, '19820322': 0.47, '19820323': 1.59, '19820324': 3.42, '19820325': 2.36, '19820326': 2.96, '19820327': 0.5, '19820328': 0.55, '19820329': 0.71, '19820330': 0.79, '19820331': 1.55, '19820401': 1.08, '19820402': 0.39, '19820403': 0.84, '19820404': 0.55, '19820405': 7.14, '19820406': 13.89, '19820407': 7.07, '19820408': 0.21, '19820409': 0.29, '19820410': 0.31, '19820411': 0.3, '19820412': 0.12, '19820413': 0.11, '19820414': 1.82, '19820415': 5.79, '19820416': 0.26, '19820417': 0.72, '19820418': 1.13, '19820419': 3.63, '19820420': 1.47, '19820421': 7.15, '19820422': 2.99, '19820423': 0.61, '19820424': 0.16, '19820425': 0.27, '19820426': 0.25, '19820427': 0.23, '19820428': 0.79, '19820429': 1.01, '19820430': 0.71, '19820501': 0.38, '19820502': 0.9, '19820503': 0.79, '19820504': 10.01, '19820505': 5.18, '19820506': 1.43, '19820507': 1.04, '19820508': 0.31, '19820509': 0.44, '19820510': 0.13, '19820511': 0.36, '19820512': 0.68, '19820513': 0.34, '19820514': 0.19, '19820515': 0.04, '19820516': 0.06, '19820517': 0.05, '19820518': 0.42, '19820519': 0.32, '19820520': 0.25, '19820521': 0.43, '19820522': 0.71, '19820523': 0.58, '19820524': 0.81, '19820525': 0.18, '19820526': 0.46, '19820527': 0.18, '19820528': 0.05, '19820529': 0.04, '19820530': 0.22, '19820531': 0.28, '19820601': 0.46, '19820602': 2.52, '19820603': 0.52, '19820604': 1.15, '19820605': 0.42, '19820606': 1.02, '19820607': 0.46, '19820608': 0.81, '19820609': 0.16, '19820610': 0.55, '19820611': 0.1, '19820612': 0.4, '19820613': 0.21, '19820614': 0.06, '19820615': 0.57, '19820616': 0.9, '19820617': 0.73, '19820618': 0.69, '19820619': 4.8, '19820620': 2.65, '19820621': 0.14, '19820622': 0.29, '19820623': 0.51, '19820624': 6.84, '19820625': 0.3, '19820626': 0.24, '19820627': 0.07, '19820628': 0.97, '19820629': 0.59, '19820630': 0.05, '19820701': 0.06, '19820702': 0.07, '19820703': 0.0, '19820704': 0.15, '19820705': 0.18, '19820706': 0.0, '19820707': 0.04, '19820708': 0.0, '19820709': 0.0, '19820710': 0.02, '19820711': 0.09, '19820712': 1.84, '19820713': 0.8, '19820714': 1.14, '19820715': 0.15, '19820716': 0.04, '19820717': 1.87, '19820718': 0.18, '19820719': 0.43, '19820720': 0.5, '19820721': 0.36, '19820722': 4.96, '19820723': 5.93, '19820724': 1.55, '19820725': 0.22, '19820726': 0.26, '19820727': 0.87, '19820728': 0.49, '19820729': 1.73, '19820730': 0.04, '19820731': 0.85, '19820801': 0.29, '19820802': 0.06, '19820803': 2.55, '19820804': 0.45, '19820805': 0.31, '19820806': 0.7, '19820807': 1.99, '19820808': 0.36, '19820809': 5.09, '19820810': 1.86, '19820811': 5.17, '19820812': 1.27, '19820813': 0.5, '19820814': 0.85, '19820815': 1.14, '19820816': 0.76, '19820817': 0.64, '19820818': 0.25, '19820819': 0.07, '19820820': 0.16, '19820821': 0.85, '19820822': 0.99, '19820823': 1.08, '19820824': 2.25, '19820825': 5.37, '19820826': 5.25, '19820827': 0.28, '19820828': 0.19, '19820829': 0.43, '19820830': 0.68, '19820831': 0.39, '19820901': 0.09, '19820902': 0.46, '19820903': 0.89, '19820904': 0.34, '19820905': 0.2, '19820906': 0.29, '19820907': 0.08, '19820908': 0.36, '19820909': 0.37, '19820910': 0.28, '19820911': 0.23, '19820912': 0.19, '19820913': 1.87, '19820914': 7.72, '19820915': 3.25, '19820916': 0.1, '19820917': 0.71, '19820918': 1.97, '19820919': 1.86, '19820920': 1.86, '19820921': 1.83, '19820922': 1.3, '19820923': 6.07, '19820924': 1.75, '19820925': 0.17, '19820926': 2.17, '19820927': 0.04, '19820928': 0.51, '19820929': 0.03, '19820930': 0.18, '19821001': 0.48, '19821002': 1.02, '19821003': 4.14, '19821004': 0.36, '19821005': 2.25, '19821006': 0.61, '19821007': 2.02, '19821008': 1.12, '19821009': 4.48, '19821010': 0.17, '19821011': 0.33, '19821012': 0.63, '19821013': 0.44, '19821014': 0.28, '19821015': 0.49, '19821016': 0.74, '19821017': 1.06, '19821018': 5.51, '19821019': 0.05, '19821020': 0.89, '19821021': 2.41, '19821022': 0.51, '19821023': 2.6, '19821024': 0.91, '19821025': 0.07, '19821026': 0.13, '19821027': 1.33, '19821028': 0.39, '19821029': 0.13, '19821030': 0.88, '19821031': 0.17, '19821101': 4.5, '19821102': 0.76, '19821103': 0.94, '19821104': 0.23, '19821105': 0.45, '19821106': 7.19, '19821107': 5.79, '19821108': 1.95, '19821109': 14.67, '19821110': 0.32, '19821111': 8.41, '19821112': 3.2, '19821113': 0.15, '19821114': 0.16, '19821115': 1.49, '19821116': 2.41, '19821117': 0.88, '19821118': 2.23, '19821119': 5.81, '19821120': 12.08, '19821121': 1.62, '19821122': 0.7, '19821123': 5.65, '19821124': 15.92, '19821125': 8.64, '19821126': 1.06, '19821127': 0.09, '19821128': 0.39, '19821129': 0.81, '19821130': 1.26, '19821201': 2.27, '19821202': 7.1, '19821203': 1.23, '19821204': 0.31, '19821205': 1.1, '19821206': 2.84, '19821207': 0.32, '19821208': 0.32, '19821209': 0.37, '19821210': 1.11, '19821211': 1.2, '19821212': 2.83, '19821213': 1.81, '19821214': 0.9, '19821215': 2.32, '19821216': 1.57, '19821217': 0.58, '19821218': 0.4, '19821219': 0.53, '19821220': 3.21, '19821221': 5.79, '19821222': 5.59, '19821223': 9.96, '19821224': 0.37, '19821225': 0.49, '19821226': 0.98, '19821227': 1.03, '19821228': 2.92, '19821229': 0.47, '19821230': 8.12, '19821231': 5.23, '19830101': 7.8, '19830102': 9.2, '19830103': 3.03, '19830104': 0.22, '19830105': 5.31, '19830106': 2.71, '19830107': 3.82, '19830108': 1.64, '19830109': 0.98, '19830110': 0.28, '19830111': 0.35, '19830112': 1.71, '19830113': 1.99, '19830114': 0.99, '19830115': 3.79, '19830116': 1.41, '19830117': 1.33, '19830118': 1.65, '19830119': 2.92, '19830120': 2.88, '19830121': 1.21, '19830122': 0.88, '19830123': 2.48, '19830124': 10.37, '19830125': 19.2, '19830126': 5.8, '19830127': 1.89, '19830128': 0.62, '19830129': 0.94, '19830130': 0.48, '19830131': 1.42, '19830201': 0.67, '19830202': 2.05, '19830203': 3.44, '19830204': 6.48, '19830205': 1.12, '19830206': 0.47, '19830207': 1.01, '19830208': 6.4, '19830209': 2.59, '19830210': 1.27, '19830211': 1.21, '19830212': 0.98, '19830213': 0.96, '19830214': 3.77, '19830215': 0.85, '19830216': 1.35, '19830217': 2.51, '19830218': 0.72, '19830219': 0.36, '19830220': 1.64, '19830221': 5.37, '19830222': 2.63, '19830223': 1.5, '19830224': 3.68, '19830225': 0.27, '19830226': 4.3, '19830227': 0.78, '19830228': 0.53, '19830301': 0.19, '19830302': 1.19, '19830303': 0.33, '19830304': 4.97, '19830305': 11.9, '19830306': 4.33, '19830307': 5.98, '19830308': 2.8, '19830309': 2.19, '19830310': 1.14, '19830311': 1.66, '19830312': 1.95, '19830313': 0.6, '19830314': 1.39, '19830315': 0.38, '19830316': 3.51, '19830317': 5.55, '19830318': 4.62, '19830319': 1.74, '19830320': 0.65, '19830321': 0.44, '19830322': 0.43, '19830323': 0.35, '19830324': 1.2, '19830325': 0.49, '19830326': 0.25, '19830327': 0.18, '19830328': 0.24, '19830329': 0.34, '19830330': 0.28, '19830331': 0.94, '19830401': 0.26, '19830402': 0.37, '19830403': 0.15, '19830404': 1.37, '19830405': 0.62, '19830406': 0.26, '19830407': 3.7, '19830408': 15.07, '19830409': 9.47, '19830410': 0.88, '19830411': 0.04, '19830412': 0.24, '19830413': 0.25, '19830414': 0.52, '19830415': 3.74, '19830416': 3.51, '19830417': 1.19, '19830418': 0.31, '19830419': 0.38, '19830420': 0.57, '19830421': 0.2, '19830422': 0.15, '19830423': 0.48, '19830424': 0.4, '19830425': 0.21, '19830426': 1.34, '19830427': 1.0, '19830428': 0.28, '19830429': 0.08, '19830430': 0.17, '19830501': 5.77, '19830502': 2.8, '19830503': 0.43, '19830504': 0.04, '19830505': 6.67, '19830506': 1.03, '19830507': 0.4, '19830508': 10.95, '19830509': 1.32, '19830510': 0.18, '19830511': 0.42, '19830512': 0.31, '19830513': 0.09, '19830514': 0.04, '19830515': 0.02, '19830516': 0.08, '19830517': 0.12, '19830518': 0.36, '19830519': 2.55, '19830520': 0.65, '19830521': 0.35, '19830522': 0.1, '19830523': 0.33, '19830524': 0.08, '19830525': 0.2, '19830526': 0.15, '19830527': 0.1, '19830528': 0.35, '19830529': 0.34, '19830530': 0.69, '19830531': 0.61, '19830601': 0.43, '19830602': 1.21, '19830603': 0.36, '19830604': 0.21, '19830605': 0.03, '19830606': 0.44, '19830607': 1.79, '19830608': 1.49, '19830609': 0.25, '19830610': 4.87, '19830611': 7.95, '19830612': 1.11, '19830613': 5.14, '19830614': 1.31, '19830615': 0.13, '19830616': 0.04, '19830617': 0.81, '19830618': 0.59, '19830619': 1.94, '19830620': 0.43, '19830621': 1.12, '19830622': 0.03, '19830623': 0.68, '19830624': 0.42, '19830625': 0.83, '19830626': 2.58, '19830627': 0.49, '19830628': 0.0, '19830629': 0.01, '19830630': 0.17, '19830701': 1.36, '19830702': 1.44, '19830703': 0.05, '19830704': 0.94, '19830705': 2.67, '19830706': 0.5, '19830707': 0.26, '19830708': 0.19, '19830709': 2.45, '19830710': 5.17, '19830711': 0.24, '19830712': 0.06, '19830713': 0.13, '19830714': 1.73, '19830715': 1.47, '19830716': 1.92, '19830717': 1.19, '19830718': 0.04, '19830719': 0.02, '19830720': 0.01, '19830721': 0.68, '19830722': 3.71, '19830723': 1.98, '19830724': 0.98, '19830725': 0.79, '19830726': 0.13, '19830727': 0.04, '19830728': 0.07, '19830729': 0.01, '19830730': 0.15, '19830731': 0.22, '19830801': 0.19, '19830802': 0.09, '19830803': 1.49, '19830804': 1.67, '19830805': 0.06, '19830806': 0.19, '19830807': 1.1, '19830808': 0.78, '19830809': 0.64, '19830810': 4.35, '19830811': 7.61, '19830812': 5.21, '19830813': 3.05, '19830814': 0.95, '19830815': 3.47, '19830816': 0.32, '19830817': 0.07, '19830818': 0.41, '19830819': 0.24, '19830820': 0.13, '19830821': 0.02, '19830822': 1.22, '19830823': 31.97, '19830824': 0.88, '19830825': 0.31, '19830826': 0.01, '19830827': 0.28, '19830828': 0.09, '19830829': 0.13, '19830830': 4.12, '19830831': 4.23, '19830901': 0.19, '19830902': 0.18, '19830903': 4.86, '19830904': 0.24, '19830905': 20.47, '19830906': 9.31, '19830907': 5.8, '19830908': 1.3, '19830909': 2.08, '19830910': 1.13, '19830911': 2.11, '19830912': 5.34, '19830913': 1.39, '19830914': 5.43, '19830915': 0.48, '19830916': 0.2, '19830917': 0.06, '19830918': 0.51, '19830919': 2.48, '19830920': 1.11, '19830921': 0.35, '19830922': 0.16, '19830923': 10.56, '19830924': 9.8, '19830925': 14.51, '19830926': 5.44, '19830927': 2.9, '19830928': 0.78, '19830929': 9.19, '19830930': 8.71, '19831001': 0.97, '19831002': 0.69, '19831003': 2.21, '19831004': 0.64, '19831005': 0.55, '19831006': 2.12, '19831007': 0.29, '19831008': 0.17, '19831009': 0.83, '19831010': 3.33, '19831011': 0.69, '19831012': 1.25, '19831013': 0.06, '19831014': 0.92, '19831015': 7.54, '19831016': 6.57, '19831017': 4.01, '19831018': 0.49, '19831019': 0.5, '19831020': 0.34, '19831021': 1.3, '19831022': 0.84, '19831023': 0.57, '19831024': 0.34, '19831025': 0.56, '19831026': 2.17, '19831027': 2.38, '19831028': 2.35, '19831029': 2.95, '19831030': 0.96, '19831031': 1.23, '19831101': 1.77, '19831102': 0.84, '19831103': 1.08, '19831104': 0.41, '19831105': 0.47, '19831106': 0.59, '19831107': 0.65, '19831108': 1.13, '19831109': 1.1, '19831110': 0.21, '19831111': 0.14, '19831112': 1.67, '19831113': 1.98, '19831114': 0.49, '19831115': 0.3, '19831116': 1.72, '19831117': 3.09, '19831118': 0.84, '19831119': 0.87, '19831120': 0.91, '19831121': 1.51, '19831122': 1.14, '19831123': 1.69, '19831124': 5.0, '19831125': 0.88, '19831126': 0.91, '19831127': 0.32, '19831128': 0.59, '19831129': 0.37, '19831130': 0.3, '19831201': 0.42, '19831202': 1.67, '19831203': 0.24, '19831204': 0.29, '19831205': 0.53, '19831206': 1.58, '19831207': 1.38, '19831208': 1.11, '19831209': 0.81, '19831210': 1.12, '19831211': 0.45, '19831212': 0.76, '19831213': 0.54, '19831214': 0.66, '19831215': 1.21, '19831216': 0.6, '19831217': 0.51, '19831218': 1.02, '19831219': 0.26, '19831220': 0.89, '19831221': 1.09, '19831222': 1.15, '19831223': 0.72, '19831224': 0.86, '19831225': 0.73, '19831226': 0.3, '19831227': 0.52, '19831228': 0.27, '19831229': 0.17, '19831230': 0.53, '19831231': 2.64, '19840101': 5.98, '19840102': 2.0, '19840103': 1.32, '19840104': 0.41, '19840105': 0.49, '19840106': 0.42, '19840107': 0.21, '19840108': 0.61, '19840109': 2.9, '19840110': 9.49, '19840111': 15.44, '19840112': 5.32, '19840113': 8.97, '19840114':

(           date  precipitation
 0      19810101           1.67
 1      19810102           0.55
 2      19810103           0.92
 3      19810104           0.44
 4      19810105           0.35
 ...         ...            ...
 16430  20251226           0.42
 16431  20251227           0.94
 16432  20251228           2.03
 16433  20251229           0.88
 16434  20251230           1.09

 [16435 rows x 2 columns],
    Latitude  Longitude  Elevation(in m)
 0    20.594       79.0           209.58)

In [2]:
precipation_df , coordinates = get_precipitation( 19810101 , 20251230 ,20.593684 ,79 )

{'type': 'Feature', 'geometry': {'type': 'Point', 'coordinates': [20.594, 79.0, 209.58]}, 'properties': {'parameter': {'PRECTOTCORR': {'19810101': 1.67, '19810102': 0.55, '19810103': 0.92, '19810104': 0.44, '19810105': 0.35, '19810106': 0.43, '19810107': 0.63, '19810108': 3.78, '19810109': 5.04, '19810110': 1.06, '19810111': 0.64, '19810112': 0.26, '19810113': 0.65, '19810114': 1.1, '19810115': 0.59, '19810116': 0.83, '19810117': 0.9, '19810118': 0.89, '19810119': 0.39, '19810120': 3.39, '19810121': 1.44, '19810122': 2.9, '19810123': 8.79, '19810124': 1.04, '19810125': 0.83, '19810126': 1.64, '19810127': 1.85, '19810128': 0.65, '19810129': 0.43, '19810130': 0.43, '19810131': 1.46, '19810201': 9.9, '19810202': 0.85, '19810203': 3.41, '19810204': 0.79, '19810205': 0.67, '19810206': 3.01, '19810207': 8.46, '19810208': 12.91, '19810209': 7.97, '19810210': 5.5, '19810211': 0.46, '19810212': 0.53, '19810213': 1.2, '19810214': 1.51, '19810215': 0.58, '19810216': 5.01, '19810217': 1.57, '19810218': 1.58, '19810219': 2.27, '19810220': 2.06, '19810221': 9.76, '19810222': 1.32, '19810223': 1.4, '19810224': 0.62, '19810225': 0.44, '19810226': 5.21, '19810227': 0.49, '19810228': 1.0, '19810301': 0.68, '19810302': 0.46, '19810303': 0.39, '19810304': 0.59, '19810305': 1.36, '19810306': 2.39, '19810307': 5.42, '19810308': 5.38, '19810309': 1.92, '19810310': 1.7, '19810311': 2.12, '19810312': 3.29, '19810313': 1.17, '19810314': 0.77, '19810315': 0.63, '19810316': 0.77, '19810317': 0.74, '19810318': 0.79, '19810319': 1.14, '19810320': 0.81, '19810321': 0.84, '19810322': 0.68, '19810323': 0.57, '19810324': 0.28, '19810325': 0.26, '19810326': 0.42, '19810327': 0.07, '19810328': 1.07, '19810329': 6.5, '19810330': 0.22, '19810331': 0.13, '19810401': 0.81, '19810402': 0.59, '19810403': 0.9, '19810404': 3.44, '19810405': 12.85, '19810406': 1.69, '19810407': 0.24, '19810408': 0.42, '19810409': 3.51, '19810410': 3.0, '19810411': 0.16, '19810412': 0.58, '19810413': 0.61, '19810414': 0.19, '19810415': 0.15, '19810416': 1.78, '19810417': 1.73, '19810418': 0.28, '19810419': 0.38, '19810420': 0.69, '19810421': 0.53, '19810422': 1.0, '19810423': 0.81, '19810424': 0.39, '19810425': 0.92, '19810426': 0.64, '19810427': 0.38, '19810428': 0.38, '19810429': 0.52, '19810430': 0.46, '19810501': 0.3, '19810502': 0.8, '19810503': 3.69, '19810504': 0.89, '19810505': 0.55, '19810506': 0.33, '19810507': 0.32, '19810508': 0.07, '19810509': 0.44, '19810510': 0.69, '19810511': 0.17, '19810512': 1.35, '19810513': 0.7, '19810514': 0.05, '19810515': 2.79, '19810516': 2.99, '19810517': 0.21, '19810518': 0.1, '19810519': 0.05, '19810520': 3.41, '19810521': 2.45, '19810522': 3.55, '19810523': 0.06, '19810524': 0.15, '19810525': 0.47, '19810526': 0.06, '19810527': 0.03, '19810528': 0.19, '19810529': 0.3, '19810530': 2.31, '19810531': 0.38, '19810601': 0.11, '19810602': 0.51, '19810603': 2.05, '19810604': 1.19, '19810605': 2.09, '19810606': 4.85, '19810607': 3.49, '19810608': 1.98, '19810609': 4.23, '19810610': 3.56, '19810611': 25.65, '19810612': 1.85, '19810613': 6.89, '19810614': 2.14, '19810615': 5.45, '19810616': 10.88, '19810617': 1.67, '19810618': 0.27, '19810619': 0.6, '19810620': 0.42, '19810621': 0.16, '19810622': 0.52, '19810623': 0.07, '19810624': 0.47, '19810625': 1.05, '19810626': 0.01, '19810627': 0.02, '19810628': 0.03, '19810629': 0.53, '19810630': 0.21, '19810701': 0.01, '19810702': 0.01, '19810703': 0.01, '19810704': 0.19, '19810705': 5.83, '19810706': 4.91, '19810707': 0.02, '19810708': 0.19, '19810709': 0.21, '19810710': 1.94, '19810711': 1.74, '19810712': 3.34, '19810713': 1.08, '19810714': 0.13, '19810715': 0.52, '19810716': 0.26, '19810717': 0.58, '19810718': 0.07, '19810719': 0.13, '19810720': 0.24, '19810721': 0.43, '19810722': 0.48, '19810723': 0.02, '19810724': 19.67, '19810725': 0.14, '19810726': 0.96, '19810727': 2.21, '19810728': 9.06, '19810729': 0.3, '19810730': 0.58, '19810731': 0.34, '19810801': 0.1, '19810802': 0.65, '19810803': 1.01, '19810804': 13.29, '19810805': 2.62, '19810806': 0.42, '19810807': 0.18, '19810808': 0.03, '19810809': 0.23, '19810810': 1.28, '19810811': 0.4, '19810812': 0.52, '19810813': 5.66, '19810814': 0.4, '19810815': 0.29, '19810816': 1.41, '19810817': 0.1, '19810818': 0.07, '19810819': 0.02, '19810820': 0.1, '19810821': 0.01, '19810822': 0.01, '19810823': 0.21, '19810824': 0.29, '19810825': 0.57, '19810826': 0.61, '19810827': 0.13, '19810828': 1.12, '19810829': 0.74, '19810830': 9.86, '19810831': 3.05, '19810901': 0.7, '19810902': 1.43, '19810903': 1.67, '19810904': 2.7, '19810905': 11.07, '19810906': 6.03, '19810907': 5.66, '19810908': 2.08, '19810909': 2.81, '19810910': 1.83, '19810911': 1.46, '19810912': 0.89, '19810913': 0.82, '19810914': 0.21, '19810915': 0.25, '19810916': 0.79, '19810917': 0.24, '19810918': 3.75, '19810919': 16.33, '19810920': 1.49, '19810921': 0.45, '19810922': 8.75, '19810923': 2.5, '19810924': 3.8, '19810925': 0.75, '19810926': 7.44, '19810927': 0.29, '19810928': 0.25, '19810929': 0.27, '19810930': 0.58, '19811001': 0.3, '19811002': 0.14, '19811003': 0.94, '19811004': 2.11, '19811005': 0.76, '19811006': 1.03, '19811007': 1.05, '19811008': 1.48, '19811009': 1.58, '19811010': 1.58, '19811011': 4.24, '19811012': 4.08, '19811013': 3.29, '19811014': 8.99, '19811015': 1.53, '19811016': 2.86, '19811017': 0.68, '19811018': 1.4, '19811019': 1.79, '19811020': 1.13, '19811021': 0.17, '19811022': 0.16, '19811023': 0.2, '19811024': 0.57, '19811025': 0.5, '19811026': 0.78, '19811027': 1.04, '19811028': 0.67, '19811029': 0.14, '19811030': 0.8, '19811031': 1.94, '19811101': 1.55, '19811102': 0.73, '19811103': 1.02, '19811104': 0.41, '19811105': 0.54, '19811106': 0.25, '19811107': 1.18, '19811108': 1.59, '19811109': 2.8, '19811110': 6.69, '19811111': 1.93, '19811112': 0.88, '19811113': 0.98, '19811114': 0.89, '19811115': 3.54, '19811116': 6.76, '19811117': 6.22, '19811118': 1.45, '19811119': 5.08, '19811120': 12.91, '19811121': 5.72, '19811122': 5.45, '19811123': 2.88, '19811124': 1.75, '19811125': 0.68, '19811126': 0.28, '19811127': 0.6, '19811128': 0.87, '19811129': 0.3, '19811130': 1.38, '19811201': 2.59, '19811202': 1.46, '19811203': 1.03, '19811204': 0.51, '19811205': 0.31, '19811206': 0.79, '19811207': 0.7, '19811208': 0.83, '19811209': 1.37, '19811210': 1.7, '19811211': 1.09, '19811212': 0.68, '19811213': 0.63, '19811214': 0.7, '19811215': 0.78, '19811216': 0.7, '19811217': 0.76, '19811218': 0.71, '19811219': 0.83, '19811220': 0.65, '19811221': 2.3, '19811222': 4.61, '19811223': 0.28, '19811224': 0.3, '19811225': 0.29, '19811226': 0.41, '19811227': 1.63, '19811228': 0.49, '19811229': 0.35, '19811230': 0.45, '19811231': 0.73, '19820101': 1.05, '19820102': 0.16, '19820103': 0.58, '19820104': 0.26, '19820105': 0.54, '19820106': 0.39, '19820107': 1.57, '19820108': 0.37, '19820109': 0.34, '19820110': 1.88, '19820111': 1.77, '19820112': 0.77, '19820113': 0.67, '19820114': 3.44, '19820115': 1.16, '19820116': 6.01, '19820117': 5.93, '19820118': 4.68, '19820119': 0.36, '19820120': 0.63, '19820121': 0.75, '19820122': 0.8, '19820123': 0.9, '19820124': 0.92, '19820125': 1.26, '19820126': 0.81, '19820127': 0.61, '19820128': 0.39, '19820129': 0.46, '19820130': 0.44, '19820131': 0.55, '19820201': 0.53, '19820202': 0.42, '19820203': 0.67, '19820204': 0.37, '19820205': 0.11, '19820206': 0.56, '19820207': 0.53, '19820208': 1.0, '19820209': 2.94, '19820210': 10.11, '19820211': 1.08, '19820212': 2.91, '19820213': 0.36, '19820214': 0.33, '19820215': 0.42, '19820216': 0.28, '19820217': 0.21, '19820218': 1.99, '19820219': 0.46, '19820220': 0.59, '19820221': 2.17, '19820222': 2.34, '19820223': 0.52, '19820224': 0.93, '19820225': 0.5, '19820226': 0.59, '19820227': 3.16, '19820228': 4.8, '19820301': 8.98, '19820302': 1.23, '19820303': 0.64, '19820304': 0.35, '19820305': 0.65, '19820306': 0.45, '19820307': 5.01, '19820308': 0.87, '19820309': 1.75, '19820310': 1.8, '19820311': 0.62, '19820312': 0.72, '19820313': 1.76, '19820314': 0.78, '19820315': 3.34, '19820316': 3.63, '19820317': 1.21, '19820318': 0.61, '19820319': 0.26, '19820320': 0.24, '19820321': 0.33, '19820322': 0.47, '19820323': 1.59, '19820324': 3.42, '19820325': 2.36, '19820326': 2.96, '19820327': 0.5, '19820328': 0.55, '19820329': 0.71, '19820330': 0.79, '19820331': 1.55, '19820401': 1.08, '19820402': 0.39, '19820403': 0.84, '19820404': 0.55, '19820405': 7.14, '19820406': 13.89, '19820407': 7.07, '19820408': 0.21, '19820409': 0.29, '19820410': 0.31, '19820411': 0.3, '19820412': 0.12, '19820413': 0.11, '19820414': 1.82, '19820415': 5.79, '19820416': 0.26, '19820417': 0.72, '19820418': 1.13, '19820419': 3.63, '19820420': 1.47, '19820421': 7.15, '19820422': 2.99, '19820423': 0.61, '19820424': 0.16, '19820425': 0.27, '19820426': 0.25, '19820427': 0.23, '19820428': 0.79, '19820429': 1.01, '19820430': 0.71, '19820501': 0.38, '19820502': 0.9, '19820503': 0.79, '19820504': 10.01, '19820505': 5.18, '19820506': 1.43, '19820507': 1.04, '19820508': 0.31, '19820509': 0.44, '19820510': 0.13, '19820511': 0.36, '19820512': 0.68, '19820513': 0.34, '19820514': 0.19, '19820515': 0.04, '19820516': 0.06, '19820517': 0.05, '19820518': 0.42, '19820519': 0.32, '19820520': 0.25, '19820521': 0.43, '19820522': 0.71, '19820523': 0.58, '19820524': 0.81, '19820525': 0.18, '19820526': 0.46, '19820527': 0.18, '19820528': 0.05, '19820529': 0.04, '19820530': 0.22, '19820531': 0.28, '19820601': 0.46, '19820602': 2.52, '19820603': 0.52, '19820604': 1.15, '19820605': 0.42, '19820606': 1.02, '19820607': 0.46, '19820608': 0.81, '19820609': 0.16, '19820610': 0.55, '19820611': 0.1, '19820612': 0.4, '19820613': 0.21, '19820614': 0.06, '19820615': 0.57, '19820616': 0.9, '19820617': 0.73, '19820618': 0.69, '19820619': 4.8, '19820620': 2.65, '19820621': 0.14, '19820622': 0.29, '19820623': 0.51, '19820624': 6.84, '19820625': 0.3, '19820626': 0.24, '19820627': 0.07, '19820628': 0.97, '19820629': 0.59, '19820630': 0.05, '19820701': 0.06, '19820702': 0.07, '19820703': 0.0, '19820704': 0.15, '19820705': 0.18, '19820706': 0.0, '19820707': 0.04, '19820708': 0.0, '19820709': 0.0, '19820710': 0.02, '19820711': 0.09, '19820712': 1.84, '19820713': 0.8, '19820714': 1.14, '19820715': 0.15, '19820716': 0.04, '19820717': 1.87, '19820718': 0.18, '19820719': 0.43, '19820720': 0.5, '19820721': 0.36, '19820722': 4.96, '19820723': 5.93, '19820724': 1.55, '19820725': 0.22, '19820726': 0.26, '19820727': 0.87, '19820728': 0.49, '19820729': 1.73, '19820730': 0.04, '19820731': 0.85, '19820801': 0.29, '19820802': 0.06, '19820803': 2.55, '19820804': 0.45, '19820805': 0.31, '19820806': 0.7, '19820807': 1.99, '19820808': 0.36, '19820809': 5.09, '19820810': 1.86, '19820811': 5.17, '19820812': 1.27, '19820813': 0.5, '19820814': 0.85, '19820815': 1.14, '19820816': 0.76, '19820817': 0.64, '19820818': 0.25, '19820819': 0.07, '19820820': 0.16, '19820821': 0.85, '19820822': 0.99, '19820823': 1.08, '19820824': 2.25, '19820825': 5.37, '19820826': 5.25, '19820827': 0.28, '19820828': 0.19, '19820829': 0.43, '19820830': 0.68, '19820831': 0.39, '19820901': 0.09, '19820902': 0.46, '19820903': 0.89, '19820904': 0.34, '19820905': 0.2, '19820906': 0.29, '19820907': 0.08, '19820908': 0.36, '19820909': 0.37, '19820910': 0.28, '19820911': 0.23, '19820912': 0.19, '19820913': 1.87, '19820914': 7.72, '19820915': 3.25, '19820916': 0.1, '19820917': 0.71, '19820918': 1.97, '19820919': 1.86, '19820920': 1.86, '19820921': 1.83, '19820922': 1.3, '19820923': 6.07, '19820924': 1.75, '19820925': 0.17, '19820926': 2.17, '19820927': 0.04, '19820928': 0.51, '19820929': 0.03, '19820930': 0.18, '19821001': 0.48, '19821002': 1.02, '19821003': 4.14, '19821004': 0.36, '19821005': 2.25, '19821006': 0.61, '19821007': 2.02, '19821008': 1.12, '19821009': 4.48, '19821010': 0.17, '19821011': 0.33, '19821012': 0.63, '19821013': 0.44, '19821014': 0.28, '19821015': 0.49, '19821016': 0.74, '19821017': 1.06, '19821018': 5.51, '19821019': 0.05, '19821020': 0.89, '19821021': 2.41, '19821022': 0.51, '19821023': 2.6, '19821024': 0.91, '19821025': 0.07, '19821026': 0.13, '19821027': 1.33, '19821028': 0.39, '19821029': 0.13, '19821030': 0.88, '19821031': 0.17, '19821101': 4.5, '19821102': 0.76, '19821103': 0.94, '19821104': 0.23, '19821105': 0.45, '19821106': 7.19, '19821107': 5.79, '19821108': 1.95, '19821109': 14.67, '19821110': 0.32, '19821111': 8.41, '19821112': 3.2, '19821113': 0.15, '19821114': 0.16, '19821115': 1.49, '19821116': 2.41, '19821117': 0.88, '19821118': 2.23, '19821119': 5.81, '19821120': 12.08, '19821121': 1.62, '19821122': 0.7, '19821123': 5.65, '19821124': 15.92, '19821125': 8.64, '19821126': 1.06, '19821127': 0.09, '19821128': 0.39, '19821129': 0.81, '19821130': 1.26, '19821201': 2.27, '19821202': 7.1, '19821203': 1.23, '19821204': 0.31, '19821205': 1.1, '19821206': 2.84, '19821207': 0.32, '19821208': 0.32, '19821209': 0.37, '19821210': 1.11, '19821211': 1.2, '19821212': 2.83, '19821213': 1.81, '19821214': 0.9, '19821215': 2.32, '19821216': 1.57, '19821217': 0.58, '19821218': 0.4, '19821219': 0.53, '19821220': 3.21, '19821221': 5.79, '19821222': 5.59, '19821223': 9.96, '19821224': 0.37, '19821225': 0.49, '19821226': 0.98, '19821227': 1.03, '19821228': 2.92, '19821229': 0.47, '19821230': 8.12, '19821231': 5.23, '19830101': 7.8, '19830102': 9.2, '19830103': 3.03, '19830104': 0.22, '19830105': 5.31, '19830106': 2.71, '19830107': 3.82, '19830108': 1.64, '19830109': 0.98, '19830110': 0.28, '19830111': 0.35, '19830112': 1.71, '19830113': 1.99, '19830114': 0.99, '19830115': 3.79, '19830116': 1.41, '19830117': 1.33, '19830118': 1.65, '19830119': 2.92, '19830120': 2.88, '19830121': 1.21, '19830122': 0.88, '19830123': 2.48, '19830124': 10.37, '19830125': 19.2, '19830126': 5.8, '19830127': 1.89, '19830128': 0.62, '19830129': 0.94, '19830130': 0.48, '19830131': 1.42, '19830201': 0.67, '19830202': 2.05, '19830203': 3.44, '19830204': 6.48, '19830205': 1.12, '19830206': 0.47, '19830207': 1.01, '19830208': 6.4, '19830209': 2.59, '19830210': 1.27, '19830211': 1.21, '19830212': 0.98, '19830213': 0.96, '19830214': 3.77, '19830215': 0.85, '19830216': 1.35, '19830217': 2.51, '19830218': 0.72, '19830219': 0.36, '19830220': 1.64, '19830221': 5.37, '19830222': 2.63, '19830223': 1.5, '19830224': 3.68, '19830225': 0.27, '19830226': 4.3, '19830227': 0.78, '19830228': 0.53, '19830301': 0.19, '19830302': 1.19, '19830303': 0.33, '19830304': 4.97, '19830305': 11.9, '19830306': 4.33, '19830307': 5.98, '19830308': 2.8, '19830309': 2.19, '19830310': 1.14, '19830311': 1.66, '19830312': 1.95, '19830313': 0.6, '19830314': 1.39, '19830315': 0.38, '19830316': 3.51, '19830317': 5.55, '19830318': 4.62, '19830319': 1.74, '19830320': 0.65, '19830321': 0.44, '19830322': 0.43, '19830323': 0.35, '19830324': 1.2, '19830325': 0.49, '19830326': 0.25, '19830327': 0.18, '19830328': 0.24, '19830329': 0.34, '19830330': 0.28, '19830331': 0.94, '19830401': 0.26, '19830402': 0.37, '19830403': 0.15, '19830404': 1.37, '19830405': 0.62, '19830406': 0.26, '19830407': 3.7, '19830408': 15.07, '19830409': 9.47, '19830410': 0.88, '19830411': 0.04, '19830412': 0.24, '19830413': 0.25, '19830414': 0.52, '19830415': 3.74, '19830416': 3.51, '19830417': 1.19, '19830418': 0.31, '19830419': 0.38, '19830420': 0.57, '19830421': 0.2, '19830422': 0.15, '19830423': 0.48, '19830424': 0.4, '19830425': 0.21, '19830426': 1.34, '19830427': 1.0, '19830428': 0.28, '19830429': 0.08, '19830430': 0.17, '19830501': 5.77, '19830502': 2.8, '19830503': 0.43, '19830504': 0.04, '19830505': 6.67, '19830506': 1.03, '19830507': 0.4, '19830508': 10.95, '19830509': 1.32, '19830510': 0.18, '19830511': 0.42, '19830512': 0.31, '19830513': 0.09, '19830514': 0.04, '19830515': 0.02, '19830516': 0.08, '19830517': 0.12, '19830518': 0.36, '19830519': 2.55, '19830520': 0.65, '19830521': 0.35, '19830522': 0.1, '19830523': 0.33, '19830524': 0.08, '19830525': 0.2, '19830526': 0.15, '19830527': 0.1, '19830528': 0.35, '19830529': 0.34, '19830530': 0.69, '19830531': 0.61, '19830601': 0.43, '19830602': 1.21, '19830603': 0.36, '19830604': 0.21, '19830605': 0.03, '19830606': 0.44, '19830607': 1.79, '19830608': 1.49, '19830609': 0.25, '19830610': 4.87, '19830611': 7.95, '19830612': 1.11, '19830613': 5.14, '19830614': 1.31, '19830615': 0.13, '19830616': 0.04, '19830617': 0.81, '19830618': 0.59, '19830619': 1.94, '19830620': 0.43, '19830621': 1.12, '19830622': 0.03, '19830623': 0.68, '19830624': 0.42, '19830625': 0.83, '19830626': 2.58, '19830627': 0.49, '19830628': 0.0, '19830629': 0.01, '19830630': 0.17, '19830701': 1.36, '19830702': 1.44, '19830703': 0.05, '19830704': 0.94, '19830705': 2.67, '19830706': 0.5, '19830707': 0.26, '19830708': 0.19, '19830709': 2.45, '19830710': 5.17, '19830711': 0.24, '19830712': 0.06, '19830713': 0.13, '19830714': 1.73, '19830715': 1.47, '19830716': 1.92, '19830717': 1.19, '19830718': 0.04, '19830719': 0.02, '19830720': 0.01, '19830721': 0.68, '19830722': 3.71, '19830723': 1.98, '19830724': 0.98, '19830725': 0.79, '19830726': 0.13, '19830727': 0.04, '19830728': 0.07, '19830729': 0.01, '19830730': 0.15, '19830731': 0.22, '19830801': 0.19, '19830802': 0.09, '19830803': 1.49, '19830804': 1.67, '19830805': 0.06, '19830806': 0.19, '19830807': 1.1, '19830808': 0.78, '19830809': 0.64, '19830810': 4.35, '19830811': 7.61, '19830812': 5.21, '19830813': 3.05, '19830814': 0.95, '19830815': 3.47, '19830816': 0.32, '19830817': 0.07, '19830818': 0.41, '19830819': 0.24, '19830820': 0.13, '19830821': 0.02, '19830822': 1.22, '19830823': 31.97, '19830824': 0.88, '19830825': 0.31, '19830826': 0.01, '19830827': 0.28, '19830828': 0.09, '19830829': 0.13, '19830830': 4.12, '19830831': 4.23, '19830901': 0.19, '19830902': 0.18, '19830903': 4.86, '19830904': 0.24, '19830905': 20.47, '19830906': 9.31, '19830907': 5.8, '19830908': 1.3, '19830909': 2.08, '19830910': 1.13, '19830911': 2.11, '19830912': 5.34, '19830913': 1.39, '19830914': 5.43, '19830915': 0.48, '19830916': 0.2, '19830917': 0.06, '19830918': 0.51, '19830919': 2.48, '19830920': 1.11, '19830921': 0.35, '19830922': 0.16, '19830923': 10.56, '19830924': 9.8, '19830925': 14.51, '19830926': 5.44, '19830927': 2.9, '19830928': 0.78, '19830929': 9.19, '19830930': 8.71, '19831001': 0.97, '19831002': 0.69, '19831003': 2.21, '19831004': 0.64, '19831005': 0.55, '19831006': 2.12, '19831007': 0.29, '19831008': 0.17, '19831009': 0.83, '19831010': 3.33, '19831011': 0.69, '19831012': 1.25, '19831013': 0.06, '19831014': 0.92, '19831015': 7.54, '19831016': 6.57, '19831017': 4.01, '19831018': 0.49, '19831019': 0.5, '19831020': 0.34, '19831021': 1.3, '19831022': 0.84, '19831023': 0.57, '19831024': 0.34, '19831025': 0.56, '19831026': 2.17, '19831027': 2.38, '19831028': 2.35, '19831029': 2.95, '19831030': 0.96, '19831031': 1.23, '19831101': 1.77, '19831102': 0.84, '19831103': 1.08, '19831104': 0.41, '19831105': 0.47, '19831106': 0.59, '19831107': 0.65, '19831108': 1.13, '19831109': 1.1, '19831110': 0.21, '19831111': 0.14, '19831112': 1.67, '19831113': 1.98, '19831114': 0.49, '19831115': 0.3, '19831116': 1.72, '19831117': 3.09, '19831118': 0.84, '19831119': 0.87, '19831120': 0.91, '19831121': 1.51, '19831122': 1.14, '19831123': 1.69, '19831124': 5.0, '19831125': 0.88, '19831126': 0.91, '19831127': 0.32, '19831128': 0.59, '19831129': 0.37, '19831130': 0.3, '19831201': 0.42, '19831202': 1.67, '19831203': 0.24, '19831204': 0.29, '19831205': 0.53, '19831206': 1.58, '19831207': 1.38, '19831208': 1.11, '19831209': 0.81, '19831210': 1.12, '19831211': 0.45, '19831212': 0.76, '19831213': 0.54, '19831214': 0.66, '19831215': 1.21, '19831216': 0.6, '19831217': 0.51, '19831218': 1.02, '19831219': 0.26, '19831220': 0.89, '19831221': 1.09, '19831222': 1.15, '19831223': 0.72, '19831224': 0.86, '19831225': 0.73, '19831226': 0.3, '19831227': 0.52, '19831228': 0.27, '19831229': 0.17, '19831230': 0.53, '19831231': 2.64, '19840101': 5.98, '19840102': 2.0, '19840103': 1.32, '19840104': 0.41, '19840105': 0.49, '19840106': 0.42, '19840107': 0.21, '19840108': 0.61, '19840109': 2.9, '19840110': 9.49, '19840111': 15.44, '19840112': 5.32, '19840113': 8.97, '19840114':

In [49]:
import requests 
import pandas as pd

def renew_eng_consum( ):

# | Indicator Code           | Description                            | Unit |
# |
# | ``EN.GHG.CO2.MT.CE.AR5`` | Total CO₂ emissions (excluding LULUCF) | Mt CO₂e |
# | ``EN.GHG.CO2.PC.CE.AR5`` | CO₂ emissions per capita (excluding LULUCF) | t CO₂e per person |

    # url = (f'https://api.worldbank.org/v2/country/ALL/indicator/EG.FEC.RNEW.ZS?format=json&per_page=500')
    meta_url = (f'https://api.worldbank.org/v2/indicator/EG.FEC.RNEW.ZS?format=json')

    # since this api retun data in multiple pages so loopin through pages
    all_data = []
    page = 1
   

    print('Processing request...')
    while True:
        url = (f'https://api.worldbank.org/v2/country/ALL/indicator/EG.FEC.RNEW.ZS?format=json&per_page=2000&page={page}')
        r = requests.get(url , timeout = 20).json()
        
        total_pages = r[0]['pages']

        print(f"\rFetching page {page}/{total_pages}...", end='', flush=True)
        all_data.extend(r[1])
        if page >= r[0]['pages']:
            break
        else:
            page += 1
    print(f'\nDone. Collected {len(all_data)} records .')


     
    meta_response = requests.get(meta_url)
    metadata = meta_response.json()[1][0]

 # converting data into DataFrame
    print('converting into DataFrame')
    df = pd.DataFrame(all_data)        
    df = df[['date' , 'value' , 'countryiso3code' ,'country'  ]]
    df['country'] = df['country'].apply(lambda x: x.get('value') if isinstance(x, dict) else x)

# Renaming columns
    df = df.rename(columns = {'countryiso3code' : 'Country_code'})
    df = df.rename(columns = {'date' : 'year'})

# changing data types of columnms
    df['year'] = df['year'].astype(int)
    df['value'] = df['value'].astype(float)

    print('Got dataFrame shape :' , df.shape)

    return df ,metadata

In [50]:
df , metadata = renew_eng_consum( )

Processing request...
Fetching page 9/9...
Done. Collected 17490 records .
converting into DataFrame
Got dataFrame shape : (17490, 4)

In [51]:
metadata
df = df.dropna()

In [52]:
df.head()

   year      value Country_code                      country
5  2020  65.782380          AFE  Africa Eastern and Southern
6  2019  62.690710          AFE  Africa Eastern and Southern
7  2018  61.587530          AFE  Africa Eastern and Southern
8  2017  61.426950          AFE  Africa Eastern and Southern
9  2016  61.822884          AFE  Africa Eastern and Southern

In [53]:
print(df["Country_code"].nunique())
print("India present:", "IND" in df["Country_code"].unique())
df

256
India present: True

       year      value Country_code                      country
5      2020  65.782380          AFE  Africa Eastern and Southern
6      2019  62.690710          AFE  Africa Eastern and Southern
7      2018  61.587530          AFE  Africa Eastern and Southern
8      2017  61.426950          AFE  Africa Eastern and Southern
9      2016  61.822884          AFE  Africa Eastern and Southern
...     ...        ...          ...                          ...
17455  1994  68.500000          ZWE                     Zimbabwe
17456  1993  64.400000          ZWE                     Zimbabwe
17457  1992  64.400000          ZWE                     Zimbabwe
17458  1991  63.700000          ZWE                     Zimbabwe
17459  1990  64.000000          ZWE                     Zimbabwe

[8203 rows x 4 columns]